# Created using wingetcreate 1.10.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: wgh136.venera
PackageVersion: 1.4.6
PackageLocale: en-US
Publisher: wgh136
PublisherUrl: https://github.com/venera-app
PublisherSupportUrl: https://github.com/venera-app/venera/issues
PackageName: Venera
PackageUrl: https://github.com/venera-app/venera
License: GPL-3.0
Copyright: GPL-3.0
ShortDescription: A comic reader that support reading local and network comics.
Tags:
- android-app
- comic
- flutter
- ios-app
- linux
- macos-app
- windows-app
ReleaseNotesUrl: https://github.com/venera-app/venera/releases/tag/v1.4.6
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/venera-app/venera/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
